### PR TITLE
Lamp "SET handler returned write response value" fix

### LINKED ISSUE #1107: Lamp: characteristic SET handler returned write response value error
**Describe The Problem:**
Homebridge logs the following error when toggling a lamp accessory on or off via the Home.app: `Characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://homebridge.io/w/JtMGR for more info.`

**To Reproduce:**
Turn a lamp accessory on or off via Home.app.

**Logs:**
```
[9/9/2023, 4:41:07 PM] [homebridge-myq] Characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://homebridge.io/w/JtMGR for more info.
logger.js:121
[9/9/2023, 4:41:07 PM] [homebridge-myq] Error: 
    at On.Characteristic.characteristicWarning (/Users/tim/code/github/jarz/homebridge-myq/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at On.<anonymous> (/Users/tim/code/github/jarz/homebridge-myq/node_modules/hap-nodejs/src/lib/Characteristic.ts:2557:18)
    at step (/Users/tim/code/github/jarz/homebridge-myq/node_modules/hap-nodejs/node_modules/tslib/tslib.js:193:27)
    at Object.next (/Users/tim/code/github/jarz/homebridge-myq/node_modules/hap-nodejs/node_modules/tslib/tslib.js:174:57)
    at fulfilled (/Users/tim/code/github/jarz/homebridge-myq/node_modules/hap-nodejs/node_modules/tslib/tslib.js:164:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Homebridge Configuration:**

_N/A_

**Screenshots:**

_N/A_

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** v18.16.0
* **Homebridge-myQ Plugin Version**: 3.4.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Apple TV 4K (1st Generation) tvOS 16.5
* **Operating System and OS Version:** Docker `homebridge/homebridge@latest`

### PR DESCRIPTION
**Pull request by jarz**
Update `setLampState()` to *not* return anything since the value currently isn't used. That value triggered the warning from Homebridge.

Fixes #1107

### CODE REVIEW

File: src/myq-lamp.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ export class myQLamp extends myQAccessory {
   protected configureDevice(): void {
 
     // Save our context information before we wipe it out.
-    const lampInitialState = this.accessory.context.lampState as boolean;
+    const lampInitialState = this.accessory.context.lampState as boolean ?? false;
```
Comment (jarz) [inline src/myq-lamp.ts:16]: This line fixes #1106.

**Comment by hjdhjd** [comment]
Thanks. Can you validate the existing fix I pushed doesn't do the job?

I'd also just adjust this one to be an explicit check against truth...

File: src/myq-lamp.ts [hunk 2]
```diff
@@ -141,8 +137,6 @@ export class myQLamp extends myQAccessory {
 
     // Execute the command.
     void this.lampCommand(value);
-
-    return true;
```
Comment (jarz) [inline src/myq-lamp.ts:145]: `setLampState()` only returns `true`, so removing this return (and adjusting code paths accordingly) addresses #1107.

Alternatively, one could adjust line 57's `onSet()` call to swallow the return value.

**Review by hjdhjd — APPROVED** [review]
